### PR TITLE
Match typings to documentation

### LINKED ISSUE #79: Documentation and typings do not match
The documentation says [here](https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#views) in the text that every value in the views object must be a `Ng1ViewDeclaration`. Although, in the example a string is used as well, which works. But the type for views is

```ts
views?: {
    [key: string]: _ViewDeclaration;
}
```
I think the type of values should be  `_ViewDeclaration | string`

Also in `StateDeclaration`, the return type of redirectTo currently is
```ts
RedirectToResult | ((transition: Transition) => Promise<RedirectToResult>);
```
although the documentation says [here](https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1statedeclaration.html#redirectto) it can either be a `RedirectToResult`, or a function returning either a `Promise` or a `RedirectToResult`. So I think it should be 
```ts
RedirectToResult | ((transition: Transition) => RedirectToResult | Promise<RedirectToResult>);
```

### PR DESCRIPTION
**Pull request by eseliger**
Closes #79

### CODE REVIEW

**Comment by christopherthielen** [comment]
Whoops, I didn't notice this PR and made the changes myself :()

Sorry bout that, but I truly appreciate the PR!

Closed by 39044878194fad4ec48e9e9fc166a6feafca14f0

**Comment by eseliger** [comment]
Oh, btw, another thing I just noticed: Can't the function also return void, so no redirect is needed? I think this works, too :)

**Comment by christopherthielen** [comment]
Yeah good point. New pr? 😀

**Comment by eseliger** [comment]
Give me a minute 👍

**Pull request closed without merging**
