### PR TITLE
Fix vanilla hash location

### PR DESCRIPTION
**Pull request by skoblenick**

### CODE REVIEW

**Comment by skoblenick** [comment]
Forgive me I am not that familiar with the code base or TypeScript. This fixes the build not sure if it has the desired result. The other thing to note within this class is that the same problem could occur with `_history` however it isn't used any where is this class which is why I left it. Different commit for cleanup; not sure if it is needed or a future feature stub.

**Comment by christopherthielen** [comment]
Hey @skoblenick thanks for the PR.  I was in the middle of a refactor, and didn't intend to push the break to master.  I've since pushed the refactor up to `master` so I'm closing this PR.

I appreciate the attention, and am curious how you noticed that `master` was broken.  Are you building off `master` or something?

**Comment by skoblenick** [comment]
@christopherthielen I have forked the repo and planned on running a slightly custom build on Travis CI. I wanted to set up my own release to include it in a project. I had built locally a few days back and didn't see the issue. I only noticed master broken in during the weekend after trying to build again.

**Comment by christopherthielen** [comment]
Thanks for the response. Are you building ng1 ng2, or react?

**Pull request closed without merging**
